name: flutter_learning_test
description: A Flutter project that contains multiple learning tests.
version: 1.0.0+1

environment:
  sdk: '>=2.10.0 <2.12.0'
  flutter: '>=1.22.0'

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
